# Generated by Django 5.2.14 on 2026-05-24 13:36

import blog.models.posts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postfile",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=blog.models.posts.post_file_upload_path
            ),
        ),
    ]
