# Generated by Django 5.2.14 on 2026-05-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="blog.comment",
            ),
        ),
    ]
